//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirstApproach2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<System.DateTime> INtroduceOn { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> catId { get; set; }
        public string photo { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
